name: data_free_KD

channels:
  - pytorch
  - conda-forge

dependencies:
  # basic
  - python=3.7.10
  - numpy=1.21.1
  - ipython=7.26.0
  - jupyter=1.0.0
  - scipy=1.7.3
  - pandas=1.3.1
  - matplotlib=3.4.2
  - scikit-learn=0.24.2
  - seaborn=0.11.1 
  - pytorch=1.10.0
  - torchvision=0.11.2
  - umap-learn=0.5.2
  - tqdm==4.62.3